### ISSUE TITLE
bash: ../configure: No such file or directory

### ISSUE THREAD

**Issue by EnziinSystem** [imr/ngspice#7]
I want to build ngspice from source code:

```
wget https://github.com/imr/ngspice/archive/refs/tags/ngspice-34.tar.gz
tar -xvf ngspice-34.tar.gz

cd ngspice-ngspice-34

mkdir release && cd release

../configure  --with-x --with-readline=yes --disable-debug
```

But it did not found configure file.

`bash: ../configure: No such file or directory`

**Comment by Pursuer2** [comment]
you should run autotool first.

see also
[https://github.com/imr/ngspice/blob/master/INSTALL](url)
chapter 1.3 Install from the git repository

**Comment by imr** [comment]
partic2 is correct. You may also want to refer to https://ngspice.sourceforge.io/docs.html
