### ISSUE TITLE
S-parameter simulation with fixed frequency and sweeped inductor

### ISSUE THREAD

**Issue by adrienluitot** [imr/ngspice#9]
Hello!

I'm trying to do a S-parameter simulation with a sweep on a inductor, but with a fixed value.
My objective is then to plot Z11 vs inductor value.
But I don't know what is the best way to do it?
Also that if the number of frequency of SP LIN is equal to 1 or 2, the number of data row is equal to 1.

I tried to do it using Qucs-S, but it uses a foreach and does _N_ SP simulation (with N the number of inductor values).

**Comment by Kreijstal** [comment]
If you ever get this working, I'd like to see how you did it

**Comment by imr** [comment]
Please see the ngspice website https://ngspice.sourceforge.io/ for places to find support.
